services:
  - type: web
    name: gaps-qa
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: PORT
        value: 3000
      - key: PUBLIC_BASE_PATH
        value: /bundles
